// <auto-generated />
using Herreria_web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herreria_web.Migrations
{
    [DbContext(typeof(HerreriaDb))]
    [Migration("20220212043701_primeraPrueba")]
    partial class primeraPrueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Herreria_web.Models.CategoriaModel", b =>
                {
                    b.Property<int>("catid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("catid"), 1L, 1);

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("catid");

                    b.ToTable("CatDB");
                });

            modelBuilder.Entity("Herreria_web.Models.ProductoModel", b =>
                {
                    b.Property<int>("proid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proid"), 1L, 1);

                    b.Property<int>("catid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rutaimg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proid");

                    b.HasIndex("catid");

                    b.ToTable("ProDB");
                });

            modelBuilder.Entity("Herreria_web.Models.ProductoModel", b =>
                {
                    b.HasOne("Herreria_web.Models.CategoriaModel", "CategoriaModel")
                        .WithMany()
                        .HasForeignKey("catid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaModel");
                });
#pragma warning restore 612, 618
        }
    }
}
